PLAYER_ENTERED_LOCATION = "PLAYER_ENTERED_LOCATION"
NPC_MET = "NPC_MET"
ITEM_ACQUIRED = "ITEM_ACQUIRED"
ITEM_LOST = "ITEM_LOST"
QUEST_STARTED = "QUEST_STARTED"
QUEST_UPDATED = "QUEST_UPDATED"
QUEST_COMPLETED = "QUEST_COMPLETED"
COMBAT_STARTED = "COMBAT_STARTED"
COMBAT_ENDED = "COMBAT_ENDED"
NPC_DIED = "NPC_DIED"
PLAYER_DAMAGED = "PLAYER_DAMAGED"
DISCOVERY_MADE = "DISCOVERY_MADE"
RELATIONSHIP_CHANGED = "RELATIONSHIP_CHANGED"
PLAYER_ACTION = "PLAYER_ACTION"
SCENE_NARRATION = "SCENE_NARRATION"

ALL_EVENT_TYPES = [
    PLAYER_ENTERED_LOCATION,
    NPC_MET,
    ITEM_ACQUIRED,
    ITEM_LOST,
    QUEST_STARTED,
    QUEST_UPDATED,
    QUEST_COMPLETED,
    COMBAT_STARTED,
    COMBAT_ENDED,
    NPC_DIED,
    PLAYER_DAMAGED,
    DISCOVERY_MADE,
    RELATIONSHIP_CHANGED,
    PLAYER_ACTION,
    SCENE_NARRATION,
]
